# Generated by Django 5.2.8 on 2025-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre / Razón Social')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('cuit', models.CharField(max_length=13, unique=True, verbose_name='CUIT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
